# Model Configuration
image_model_name: "vit_base_patch16_224"
text_model_name: "openai/clip-vit-base-patch16"
image_prompt_len: 5
text_prompt_len: 5
prompt_depth: 6
fusion_dim: 512
freeze_image_encoder: false
freeze_text_encoder: false

# Training Configuration
epochs: 20
batch_size: 32
num_workers: 4
image_size: 224
lr: 0.0001
weight_decay: 0.01
seed: 42

# Data Configuration
data_dir: "./data/food101"

# Logging Configuration
save_dir: "./checkpoints"
log_dir: "./logs"
use_tensorboard: true

# Device Configuration
device: "cuda"  # "cuda" or "cpu"

# Resuming (optional)
# resume_path: "./checkpoints/model_epochX.pt"