# 实验配置
experiment_name: "food101_0509_clip_nocurrimlearn_mr0.7"

# Model Configuration
image_model_name: "openai/clip-vit-base-patch16"
text_model_name: "openai/clip-vit-base-patch16" #" "
encoder_type: "clip"  # "clip" or "roberta"
image_prompt_len: 36
text_prompt_len: 36
prompt_depth: 6
fusion_dim: 512
freeze_image_encoder: True
freeze_text_encoder: True
use_quality_prompt: True
use_cross_modal_prompt: True
max_length: 77

# Training Configuration
epochs: 20
batch_size: 16
num_workers: 4
image_size: 224
patch_size: 16
lr: 0.0001
weight_decay: 0.005
warmup_percent: 0.2
min_lr: 0.000001
seed: 66666
save_every_epochs: 20

# loss
# Recon loss
initial_recon_weight: 2
final_recon_weight: 0.5

# Cls loss
use_focal_loss: false
focal_start_epoch: 3
focal_gamma: 0.5
gamma_ramp_epochs: 5
focal_alpha: 0.1
focal_weight: 0.3

use_asymmetric_loss: false
asl_start_epoch: 5
asl_gamma_pos: 0.0
asl_gamma_neg: 4.0
asl_ramp_epochs: 3
asl_clip: 0.05


# Data Configuration
dataset: "food101"
data_dir: "./data/food101"

missing_strategy: "both"
missing_prob: 0.7
val_missing_strategy: "both"
val_missing_prob: 0.7
test_missing_strategy: "both"
test_missing_prob: 0.7

# Add after missing_prob line
initial_missing_prob: 0.7
final_missing_prob: 0.7
missing_prob_ramp_epochs: 5

# 评估指标设置
metrics: ["accuracy", "macro_f1", "micro_f1"]
primary_metric: "accuracy"

# Logging Configuration
use_tensorboard: true

# Email configuration
email:
  send_email: true
  smtp_server: "smtp.qq.com"
  smtp_port: 465
  sender_email: "1494032646@qq.com"
  sender_password: "gmhibktcmuggiiab"
  recipient_email: "aultcarius@163.com"
  email_subject: "Training Results: UPMC Food101 Experiment"

# Device Configuration
device: "cuda"  # "cuda" or "cpu"

# Resuming (optional)
#resume_path: "./checkpoints/best_model.pt"